name: Open Version

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Tipo de versão para ser aberta'
        required: true
        type: choice
        default: 'release'
        options:
          - release
          - hotfix

permissions:
  contents: write     # Permissão de escrita
  pages: write        # Permissão para páginas
  id-token: write
jobs:
  open_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Instalar jq
        run: sudo apt-get install jq  # Instala jq para manipulação de JSON

#      - name: Set up GitHub CLI
#        uses: cli/gh-action@v2
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Open version
        run: |
          chmod +x scripts/ci/open-version.sh
          ./scripts/ci/open-version.sh -type='${{github.event.inputs.version_type}}'
        env:
          PAT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT_REPO: ${{github.repository}}
          REPO_TOKEN: ${{secrets.REPO_TOKEN}}